# Novel Listener - Windows installer builder (custom version)
# Usage:
#   .\build_installer.ps1
#   .\build_installer.ps1 -Version 1.2.0
#   build_installer.bat 1.2.0

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$Version
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

$AppDir = Join-Path $Root "听小说应用"
$DistDir = Join-Path $Root "novel_listener\dist"
$Iss = Join-Path $Root "novel_listener\installer\听小说.iss"
$OutDir = Join-Path $Root "发布"
$VersionFile = Join-Path $Root "VERSION"
$DefineFile = Join-Path $Root "novel_listener\installer\version_defines.iss"

function Write-Info([string]$Message) {
    Write-Host ("[INFO] " + $Message)
}
function Write-Ok([string]$Message) {
    Write-Host ("[OK] " + $Message)
}
function Write-Warn([string]$Message) {
    Write-Host ("[WARN] " + $Message)
}

Write-Host "========================================"
Write-Host "  ListenNovel installer builder"
Write-Host "  听小说 - 生成 Windows 安装包"
Write-Host "========================================"
Write-Host ""

function Read-DefaultVersion {
    if (Test-Path -LiteralPath $VersionFile) {
        $raw = Get-Content -LiteralPath $VersionFile -Raw -Encoding UTF8
        if ($null -eq $raw) { return "1.0.0" }
        $v = $raw.Trim().Trim([char]0xFEFF)
        if ($v) { return $v }
    }
    return "1.0.0"
}

function Normalize-VersionInfo([string]$ver) {
    $parts = @($ver.Split(".") | Where-Object { $_ -ne "" })
    if ($parts.Count -lt 1 -or $parts.Count -gt 4) {
        throw "Invalid version (max 4 parts): $ver"
    }
    foreach ($p in $parts) {
        if ($p -notmatch '^\d+$') {
            throw "Version parts must be digits: $ver"
        }
    }
    while ($parts.Count -lt 4) { $parts += "0" }
    return ($parts -join ".")
}

if (-not $Version) {
    $default = Read-DefaultVersion
    Write-Host ("Default version: " + $default)
    $inputVer = Read-Host "Enter version (Enter = default)"
    if ([string]::IsNullOrWhiteSpace($inputVer)) {
        $Version = $default
    } else {
        $Version = $inputVer.Trim()
    }
} else {
    $Version = $Version.Trim()
}

if ([string]::IsNullOrWhiteSpace($Version)) {
    throw "Version is empty"
}
if ($Version -notmatch '^\d+(\.\d+){0,3}$') {
    throw ("Invalid version format: " + $Version + " (use 1.0.0 or 1.2.3.4)")
}

$VerInfo = Normalize-VersionInfo $Version

# Write VERSION as ASCII to avoid BOM/CRLF issues on next run
[System.IO.File]::WriteAllText($VersionFile, $Version + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))

Write-Info ("Installer version = " + $Version)
Write-Info ("File version      = " + $VerInfo)
Write-Host ""

$AppExe = Join-Path $AppDir "听小说.exe"
$DistExe = Join-Path $DistDir "听小说.exe"
if (-not (Test-Path -LiteralPath $AppExe)) {
    if (Test-Path -LiteralPath $DistExe) {
        Write-Info "Copy exe from dist ..."
        New-Item -ItemType Directory -Force -Path $AppDir | Out-Null
        Copy-Item -LiteralPath $DistExe -Destination $AppExe -Force
    }
}
if (-not (Test-Path -LiteralPath $AppExe)) {
    throw "Missing 听小说.exe. Run novel_listener\build_exe.bat first."
}
if (-not (Test-Path -LiteralPath $Iss)) {
    throw ("Missing ISS script: " + $Iss)
}

$isccCandidates = @(
    (Join-Path $env:LocalAppData "Programs\Inno Setup 6\ISCC.exe"),
    (Join-Path ${env:ProgramFiles(x86)} "Inno Setup 6\ISCC.exe"),
    (Join-Path $env:ProgramFiles "Inno Setup 6\ISCC.exe")
)
$Iscc = $isccCandidates | Where-Object { $_ -and (Test-Path -LiteralPath $_) } | Select-Object -First 1
if (-not $Iscc) {
    throw "ISCC.exe not found. Install: winget install JRSoftware.InnoSetup"
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

# Generate defines file as UTF-8 with BOM (Inno Setup friendly)
$defineText = @"
; auto-generated by build_installer.ps1
#define MyAppVersion "$Version"
#define MyAppVersionInfo "$VerInfo"
"@
$utf8Bom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllText($DefineFile, $defineText, $utf8Bom)

$outName = "听小说安装包_v$Version.exe"
Write-Info ("Compiling with: " + $Iscc)
Write-Info ("ISS: " + $Iss)
Write-Info ("OUT: " + (Join-Path $OutDir $outName))
Write-Host ""

& $Iscc $Iss
if ($LASTEXITCODE -ne 0) {
    throw ("ISCC failed, exit code " + $LASTEXITCODE)
}

$built = Join-Path $OutDir $outName
if (-not (Test-Path -LiteralPath $built)) {
    Write-Warn "Expected output file not found. Files in 发布:"
    Get-ChildItem -LiteralPath $OutDir -Filter "*.exe" | ForEach-Object { Write-Host (" - " + $_.Name) }
} else {
    $mb = [math]::Round((Get-Item -LiteralPath $built).Length / 1MB, 1)
    Write-Host ""
    Write-Ok ("Created: 发布\" + $outName)
    Write-Ok ("Size: " + $mb + " MB")
}

try { Invoke-Item $OutDir } catch {}
